#!/bin/sh

./build.sh

# Set directories and link.
BIN_DIR="$HOME/bin"
EXE_DIR="$HOME/bin/dotnet-solution-generator-exe"
EXE_LINK="$HOME/bin/dotnet-solution-generator"

# Remove old executable.
rm -rf "$EXE_DIR"
rm -rf "$EXE_LINK"

mkdir -p "$BIN_DIR"

cp -r "dist/dotnet-solution-generator" "$EXE_DIR"

ln -s "$EXE_DIR/Wizards.SolutionGenerator.Executable" "$EXE_LINK"

# Uncomment the following line, if you want
#   to check which shell you are using.
# echo $0

# Uncomment one of the following lines, if you want
#   to add the executable binary to your path.
# SHRC="$HOME/.zshrc"
# SHRC="$HOME/.kshrc"
# SHRC="$HOME/.bashrc"
# SHRC="$HOME/.bash_profile"
# SHRC="$HOME/.profile"

if [ ! -z "$SHRC" ]
then
  echo "\n# Add to path (autogenerated by install.sh script)." >> "$SHRC"
  echo "export PATH=\"\$PATH:$BIN_DIR\"" >> "$SHRC"
fi
